theme = "dark_high_contrast"

[editor]
mouse = false
true-color = true
line-number = "relative"
clipboard-provider = "pasteboard"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
