ln -sf /DATA  ~/DATA
ln -sf /DATA/Datasets2    ~/datasets2
ln -sf /DATA/Datasets3    ~/datasets3
ln -sf /DATA/Datasets4    ~/datasets4
ln -sf /DATA/Datasets5    ~/datasets5
ln -sf /DATA/Datasets30   ~/datasets30
ln -sf /DATA/Datasets90   ~/datasets90
ln -sf /DATA/Datasets91   ~/datasets91
ln -sf /DATA/Datasets.bak ~/datasets.bak
ln -sf /DATA/Workspace  ~/workspace
ln -sf /DATA/Videos     ~/global_videos
ln -sf /DATA/Pictures   ~/global_pictures
ln -sf /DATA/Music      ~/global_music
ln -sf /DATA/Datasets.mini ~/datasets.mini
